---
# All tasks marked by tag 'updatecheck' will be used by callback plugin
# 'hostupgradeplugin' to retrieve information about packages which
# that tasks installs or updates. So if you want to add any specific task
# analazying packages to be updates/installed please tag it by 'updatecheck'
# tag.

- name: Install ovirt-host package if it isn't installed
  yum:
    name: ovirt-host
    state: latest
    update_cache: yes
    lock_timeout: 300
  tags:
    - updatecheck
    - skip_ansible_lint # E403

- name: Import oVirt host facts
  import_role:
    name: ovirt-host-deploy-facts
    tasks_from: host-os.yml

- name: Prepare NGN host for upgrade
  file:
    path: /var/imgbased/.image-updated
    state: absent
  when: ngn_host|bool

# Ignoring empty lines and the title "Obsoleting packages"
- name: Upgrade packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    lock_timeout: 300
  loop: "{{ yum_result.split('\n') }}"
  tags:
  - updatecheck
  - skip_ansible_lint # E403
  register: updated_packages
  when: item and item != "Obsoleting"

- name: Check if image was updated
  set_fact:
    image_pkg_updated: "{{ yum_result is search('image-update') }}"
  when: ngn_host|bool

- name: Check if image-updated file exists
  stat:
    path: /var/imgbased/.image-updated
  register: image_updated_file
  when:
    - ngn_host|bool
    - image_pkg_updated|bool

- name: Verify image was updated successfully
  fail:
    msg: "NGN host upgrade failed"
  when:
    - ngn_host|bool
    - image_pkg_updated|bool
    - not image_updated_file.stat.exists
    - host_deploy_cluster_version|float >= 4.4
