---
- name: Install yum-utils
  package:
    name: yum-utils
    state: present

- name: Fetch info about VDSM
  command: "repoquery --qf '%{VERSION}' vdsm"
  changed_when: false
  register: vdsm_version
  check_mode: no
  args:
    warn: no

- name: Install Python3 for CentOS/RHEL8 hosts
  yum:
    name: python3
    state: latest
  when: ansible_distribution|map(match, ['RedHat','CentOS']) and ansible_distribution_major_version|int >= 8

- name: Set facts
  set_fact:
    host_deploy_vdsm_version: "{{ vdsm_version.stdout }}"
    ansible_python_interpreter : "{{ '/usr/bin/python3' if (ansible_distribution == 'Fedora') or (
        (
            ansible_distribution|map(match, ['RedHat','CentOS'])
        ) and (
            ansible_distribution_major_version|int >= 8
        )
    ) else '/usr/bin/python2' }}"
