---
- name: Verify that grubby package is installed
  yum:
    name: grubby
    state: latest

- name: Detect if boot parameter is set when FIPS support is enabled
  set_fact:
    add_boot_param: "{{ host_deploy_kernel_cmdline_new | regex_search('fips\\s*=\\s*1') and not host_deploy_kernel_cmdline_new | regex_search('boot\\s*=') }}"

- name: Fetch boot drive UUID
  shell: findmnt --output=UUID --noheadings --target=/boot
  register: uuid
  when: add_boot_param|bool
  failed_when: not uuid.stdout

- name: Add boot parameter to kernel parameters
  set_fact:
    host_deploy_kernel_cmdline_new: "boot=UUID={{ uuid.stdout }} {{ host_deploy_kernel_cmdline_new }}"
  when: uuid.changed|bool

- name: Removing old kernel arguments
  shell: "grubby --update-kernel DEFAULT --remove-args '{{ host_deploy_kernel_cmdline_old }}'"
  when: host_deploy_kernel_cmdline_old

- name: Adding new kernel arguments
  shell: "grubby --update-kernel DEFAULT --args '{{ host_deploy_kernel_cmdline_new }}'"
  when: host_deploy_kernel_cmdline_new
