---
- name: Validate virtualization if virt service is supported
  include_tasks: virtualization.yml
  when: host_deploy_virt_enabled|bool

- name: Include packages, vdsmid, pki and restart servives tasks
  include_tasks: "{{ item }}.yml"
  with_items:
  - packages
  - vdsmid
  - pki
  - restart_services
