---
- name: Install ovirt-host package
  yum:
    name: ovirt-host
    state: present
  tags:
    - skip_ansible_lint # E403

- name: Get packages
  package_facts:
    manager: auto

- name: Verify minimum vdsm version exists
  fail:
    msg: "Minimum version required for vdsm is {{ host_deploy_vdsm_min_version }}"
  when: host_deploy_vdsm_min_version|float < ansible_facts.packages['vdsm'][0].version|float

# Order of next steps is important:
#     1. Configure lvm filter
#     2. Configure vdsm
#
# If we configure vdsm before configuring lvm filter, multipath may
# grab local devices that should be blacklisted. This may expose
# the local devices as FC storage in engine.

- name: Configure LVM filter
  shell: vdsm-tool config-lvm-filter -y
  tags:
    - skip_ansible_lint # E305
  register: lvm_filter_result
  when: el_ver|int >= 8
  ignore_errors: true

- name: Error configuring LVM filter
  debug:
    msg: "Cannot configure LVM filter on host, please run: vdsm-tool config-lvm-filter"
  when:
    - el_ver|int >= 8
    - lvm_filter_result.rc != 0

- name: Reconfigure vdsm tool
  shell: vdsm-tool configure --force
  tags:
    - skip_ansible_lint # E305
