---
- name: Install ovirt-host package
  yum:
    name: ovirt-host
    state: present
  tags:
    - skip_ansible_lint # E403

- name: Get packages
  package_facts:
    manager: auto

- name: Verify minimum vdsm version exists
  fail:
    msg: "Minimum version required for vdsm is {{ host_deploy_vdsm_min_version }}"
  when: host_deploy_vdsm_min_version|float < ansible_facts.packages['vdsm'][0].version|float

- name: Reconfigure vdsm tool
  shell: vdsm-tool configure --force
  tags:
    - skip_ansible_lint # E305
