---
- name: Get cpu info
  slurp:
    src: "{{ cpu_info }}"
  register: cpuinfo

- name: Print performance warning message
  debug:
    msg: "Machine does not support constant timestamp counter, this may effect performance"
  when: "vendor_id in ['GenuineIntel', 'AuthenticAMD'] and 'constant_tsc' not in cpuinfo['content']|b64decode"

- name: Search for vendor id in cpu info
  set_fact:
    vendor_id_search: "{{ (cpuinfo['content']|b64decode|regex_search(vendor_id_regexp)) }}"

- name: Set vendor id
  set_fact:
    vendor_id: "{{ vendor_id_search.split(':')[1]|regex_replace(' ', '') }}"
  when: "vendor_id_search != '' and (vendor_id_search.split(':')[1]|regex_replace(' ', '') in supported_cpus)"

- block:
  - name: get vendor id if it wasnt found in file
    set_fact:
      cpu_search: "{{ (cpuinfo['content']|b64decode|regex_search(cpu_regexp)) }}"

  - name: Set vendor id by cpu
    set_fact:
      vendor_id: "{{ 'IBM_POWER' if (cpu_search != '' and 'power' in cpu_search.split(':')[1]) }}"
  when: "vendor_id_search == ''"

- name: Verify architecture is supported
  fail:
  when: "vendor_id == ''"

- name: Get flags
  set_fact:
    flags: "{{ (cpuinfo['content']|b64decode|regex_search(flags_regexp)) }}"
  when: "vendor_id in ['GenuineIntel', 'AuthenticAMD']"

- name: Get features
  set_fact:
    features: "{{ (cpuinfo['content']|b64decode|regex_search(features_regexp)) }}"
  when: "vendor_id == 'IBM/S390'"

- name: Get platform
  set_fact:
    platform: "{{ (cpuinfo['content']|b64decode|regex_search(platform_regexp)) }}"
  when: "vendor_id == 'IBM_POWER'"

- name: Verify hardware supports virtualization
  fail:
  when: >
    not (
    (vendor_id == 'GenuineIntel' and 'vmx' in flags) or
    (vendor_id == 'AuthenticAMD' and 'svm' in flags) or
    (vendor_id == 'IBM/S390' and 'sie' in features) or
    (vendor_id == 'IBM_POWER' and 'powernv' in platform))