- hosts: all
  remote_user: root

  roles:
    - role: ovirt-host-deploy
    - role: hc-gluster-cgroups
      when: host_deploy_virt_enabled and host_deploy_gluster_enabled

  tasks:
    - name: Check if post tasks file exists
      stat:
        path: "{{ host_deploy_post_tasks }}"
      delegate_to: localhost
      register: stat_post_tasks
      when: "host_deploy_post_tasks is defined"

    - name: Executing post tasks defined by user
      include: "{{ host_deploy_post_tasks }}"
      when: "host_deploy_post_tasks is defined and stat_post_tasks.stat.exists"
