---
- block:
  - name: Create cert dir
    file:
      path: "{{ host_deploy_vnc_tls_x509_cert_dir }}"
      state: directory

  - name: Setup VNC PKI
    copy:
      src: "{{ host_deploy_spice_tls_x509_cert_dir }}/{{ item }}"
      dest: "{{ host_deploy_vnc_tls_x509_cert_dir }}/{{ item }}"
      force: no
      remote_src: yes
    with_items:
      - "ca-cert.pem"
      - "server-cert.pem"
      - "server-key.pem"

  - name: Modify qemu config file - enable TLS
    blockinfile:
      path: '/etc/libvirt/qemu.conf'
      state: present
      marker: '## {mark} configuration section by vdsm-{{ host_deploy_vdsm_version }}'
      block: |
        vnc_tls=1
        vnc_tls_x509_cert_dir="{{ host_deploy_vnc_tls_x509_cert_dir }}"
    when: host_deploy_vnc_tls|bool
    notify:
      restart libvirtd

  - name: Modify qemu config file - disable TLS
    blockinfile:
      path: '/etc/libvirt/qemu.conf'
      state: absent
      marker: '## {mark} configuration section by vdsm-{{ host_deploy_vdsm_version }}'
      block: |
        vnc_tls=1
        vnc_tls_x509_cert_dir="{{ host_deploy_vnc_tls_x509_cert_dir }}"
    when: not host_deploy_vnc_tls|bool
    notify:
      restart libvirtd

